# Generated by Django 3.2.8 on 2021-12-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211211_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blanks',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-time_create', 'unikID'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
