# Generated by Django 3.2.8 on 2021-12-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211211_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.TextField(default='null', verbose_name='Абонемент'),
        ),
    ]
